OMAP4: board-4430sdp.c: Warnings cleanup
This patch fix the following compilation error:
arch/arm/mach-omap2/board-4430sdp.c:370:
warning: 'sdp4430_hdmi_init' defined but not used

Adding:
__attribute__ ((unused))

Signed-off-by: Ricardo Perez Olivares <x0081762@ti.com>