omap: 3430sdp: Fix Build error in ohci struct
This patch fixes following compilation error:

arch/arm/mach-omap2/board-3430sdp.c: In function 'omap_3430sdp_init':
arch/arm/mach-omap2/board-3430sdp.c:840: error: ohci_pdata causes a section type conflict

Introduced in after commit ID:

  commit 775bd09f78f59bcd550806fe1396ca96c49d3ee6
  Author: Anand Gadiyar <gadiyar@ti.com>
  Date:   Wed Apr 21 15:27:14 2010 +0530

      omap: 3430sdp: add ohci platform init

Signed-off-by: Sergio Aguirre <saaguirre@ti.com>