omap:hsmmc : Fix compilation break and Warning
1) Fixing below compilation break which was introduced by
   commit	c6f16caee1e19d40be194079b29bd2c2e9bed440 :

   drivers/mmc/host/omap_hsmmc.c: In function 'omap_hsmmc_probe':
   drivers/mmc/host/omap_hsmmc.c:2221: error: 'struct omap_hsmmc_host' has no member named 'name'
   drivers/mmc/host/omap_hsmmc.c:2221: error: 'struct omap_hsmmc_host' has no member named 'name'
   drivers/mmc/host/omap_hsmmc.c:2221: error: 'struct omap_mmc_slot_data' has no member named 'wired'

2) Also Fixes below compilation Warning:

   drivers/mmc/host/omap_hsmmc.c: In function 'omap_hsmmc_suspend':
   drivers/mmc/host/omap_hsmmc.c:2393: warning: unused variable 'state'

Signed-off-by: Kishore Kadiyala <kishore.kadiyala@ti.com>