Fix compile error for OMAPDSS
If DSS Debug support is removed from OMAP2/3/4 Display Subsystem support, build error was observed.

I you disable Debug support in menuconfig from Device Drivers ->
Graphics support ->  OMAP2/3/4 Display Subsystem support
and compile kernel you'll receive the following error

drivers/video/omap2/dss/dsi.c:414:26: error: duplicate macro parameter "x"
parameters should have different names.

Signed-off-by: Rogelio Garcia <x0061999@ti.com>
Signed-off-by: Mayuresh Janorkar <mayur@ti.com>