OMAP4: board_4430: Fixing compilation errors
After solve merge conflicts the following error
comes up:

board-4430sdp.c:435: error: expected expression before 'static'

This patch fix this error, putting proper definitions of:
&wl128x_device

Under structure:
static struct platform_device *sdp4430_devices[]

Signed-off-by: Ricardo Perez Olivares <x0081762@ti.com>