OMAP4: UART: Fix to prevent compilation errors on uart reverted patch
This patch fixes the compilation errors while reverting:
2c7ea3a1ace2aa70611b79e1fb8ec3d78ff1b234

when the described commit ID was reverted, the following compilation error
happens:
arch/arm/mach-omap2/serial.c:881: error:
'serial_out_override' undeclared (first use in this function)

This line was introduced by the following patch:
c269575cff43fc775758e67aeb9097497f101876 from Govindraj R
Add omap serial driver support

The patch from Govindraj do modifications to several files, but the
important lines used and modified to fix the compilation are related to:
arch/arm/mach-omap2/serial.c file

The fix consists basically in erase the lines that include the usage of
serial_out_override in the file arch/arm/mach-omap2/serial.c using as
a guide the patch provided to Govindraj in order to manually revert the lines
added in 'serial.c' file. E.g:
uart->p->serial_out = serial_out_override
(that was added with the Govindraj's patch).

Signed-off-by: Ricardo Perez Olivares <x0081762@ti.com>