OMAP: Fix omap3_defconfig build
omap3_defconfig build is broken due to non existing header file.

Error log:
arch/arm/mach-omap2/board-rx51-peripherals.c:17: fatal error: linux/spi/wl12xx.h: No such file or directory
compilation terminated.
make[1]: *** [arch/arm/mach-omap2/board-rx51-peripherals.o] Error 1
make: *** [arch/arm/mach-omap2] Error 2

Signed-off-by: G, Manjunath Kondaiah <manjugk@ti.com>