OMAP4: PM: Update omap4_pm_defconfig
Some options recently introduced cause link errors
when enabled.

  LD      .tmp_vmlinux1
  drivers/built-in.o: In function `dpi_set_mode':
  /home/x0016154/L24.0.13-new/drivers/video/omap2/dss/dpi.c:174: undefined reference to `dsi_pll_uninit'
  drivers/built-in.o: In function `notify_ducatidrv_sendevent':
  /home/x0016154/L24.0.13-new/drivers/dsp/syslink/notify_ducatidriver/notify_ducati.c:1013: undefined reference to `omap_mbox_msg_send'
  drivers/built-in.o: In function `notify_ducatidrv_setup':
  /home/x0016154/L24.0.13-new/drivers/dsp/syslink/notify_ducatidriver/notify_ducati.c:691: undefined reference to `omap_mbox_get'
  drivers/built-in.o: In function `notify_ducatidrv_destroy':
  /home/x0016154/L24.0.13-new/drivers/dsp/syslink/notify_ducatidriver/notify_ducati.c:626: undefined reference to `omap_mbox_put'
  make: *** [.tmp_vmlinux1] Error 1

These options are now disabled in omap4_pm_defconfig, but these also need to
be fixed in the respective drivers.
No kernel option should be such that enabling/disabling it causes link errors.

Signed-off-by: Rajendra Nayak <rnayak@ti.com>