ARM: fix compiling error due to debug_info change
  CC [M]  crypto/xcbc.o
In file included from /opt/git/ubuntu/roc/natty/fs/binfmt_aout.c:32:
/opt/git/ubuntu/roc/natty/arch/arm/include/asm/a.out-core.h: In function ‘aout_dump_thread’:
/opt/git/ubuntu/roc/natty/arch/arm/include/asm/a.out-core.h:35: error: ‘struct debug_info’ has no member named ‘bp’
/opt/git/ubuntu/roc/natty/arch/arm/include/asm/a.out-core.h:36: error: ‘struct debug_info’ has no member named ‘bp’
/opt/git/ubuntu/roc/natty/arch/arm/include/asm/a.out-core.h:37: error: ‘struct debug_info’ has no member named ‘bp’
/opt/git/ubuntu/roc/natty/arch/arm/include/asm/a.out-core.h:38: error: ‘struct debug_info’ has no member named ‘bp’
/opt/git/ubuntu/roc/natty/arch/arm/include/asm/a.out-core.h:39: error: ‘struct debug_info’ has no member named ‘nsaved’
make[3]: *** [fs/binfmt_aout.o] Error 1
make[2]: *** [fs] Error 2

This bug was introduced by "ARM: 6668/1: ptrace: remove single-step emulation code" from Will Deacon

Signed-off-by: Bryan Wu <bryan.wu@canonical.com>